In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("modis_2023_India.csv")

In [13]:
df.head(5)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,9.3280,77.6247,318.0,1.1,1.0,2023-01-01,821,Aqua,MODIS,62,61.03,305.0,7.6,D,0
1,10.4797,77.9378,313.8,1.0,1.0,2023-01-01,822,Aqua,MODIS,58,61.03,299.4,4.3,D,0
2,13.2478,77.2639,314.7,1.0,1.0,2023-01-01,822,Aqua,MODIS,55,61.03,302.4,4.9,D,0
3,12.2994,78.4085,314.3,1.0,1.0,2023-01-01,822,Aqua,MODIS,58,61.03,301.9,4.8,D,0
4,14.1723,75.5024,338.4,1.2,1.1,2023-01-01,823,Aqua,MODIS,88,61.03,305.3,41.5,D,0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78425 entries, 0 to 78424
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   latitude    78425 non-null  float64
 1   longitude   78425 non-null  float64
 2   brightness  78425 non-null  float64
 3   scan        78425 non-null  float64
 4   track       78425 non-null  float64
 5   acq_date    78425 non-null  object
 6   acq_time    78425 non-null  int64
 7   satellite   78425 non-null  object
 8   instrument  78425 non-null  object
 9   confidence  78425 non-null  int64
 10  version     78425 non-null  float64
 11  bright_t31  78425 non-null  float64
 12  frp         78425 non-null  float64
 13  daynight    78425 non-null  object
 14  type        78425 non-null  int64
dtypes: float64(8), int64(3), object(4)
memory usage: 9.0+ MB

In [15]:
df.isnull()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78420,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
78421,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
78422,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
78423,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
78424,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False